version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /workflows/main.wdl
    testParameterFiles:
      - /example/inputs.json
    readMePath: /README.md
    authors:
      - name: Anand Maurya
        email: anand.maurya@well.ox.ac.uk